### PR TITLE
Update checkout action to v3

### PR DESCRIPTION
**Pull request by willaerk**
### Changed

- Update checkout action to v3 to get rid of GitHub deprecation warnings for NodeJS 12.

### CODE REVIEW

**Comment by bertramakers** [comment]
It looks like this breaks all the actions @willaerk , I'll have to take a look at it later to figure out what is going wrong. But for now we should definitely not merge this

**Comment by bertramakers** [comment]
Weird thing is that I already updated the "Publish" actions to use v3 here, and those are now suddenly failing with your changes to other actions: https://github.com/cultuurnet/apidocs/pull/96/files#diff-05446e9d01a687cb5d60ba5412a5e591777fa502f5fab1a13ec79202d4d1d505L17-R17

**Comment by willaerk** [comment]
Hmmm interesting :)

**Comment by bertramakers** [comment]
FYI and note to self:
There are also two actions that are not run automatically (for every PR) that we'll need to test:

- https://github.com/cultuurnet/apidocs/actions/workflows/linting-docs-fix.yml (only runs manually to fix linting errors, Corneel uses this a lot for example so he doesn't need to set up the linter locally)
- https://github.com/cultuurnet/apidocs/actions/workflows/split-udb3-json-schemas.yml (pushes changes to `projects/uitdatabank/models` to a separate `cultuurnet/udb3-json-schemas` repo, only triggered when one of those files is changed)

**Comment by bertramakers** [comment]
@corneelwille @LucWollants feel free to ignore, the linter cleaned up some redundant whitespace in UiTdatabank Markdown files. But the rest of the PR is not relevant for UiTdatabank and more of a tooling update.

**Pull request merged**
